spring:
  application:
    name: config-single-server  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangzhuowen/springcloud-config #配置文件所在仓库
          username: zhangzhuowen
          password: Ly729475287
          default-label: master #配置文件分支
  artemis:
    port: 9999
#          search-paths: config  #配置文件所在根目录